Rails.application.routes.draw do
  # Devise routes
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Redirect to this page upon entering webpage
  root to: 'pages#home'

  # Static page generated by 'about' method in pages controller
  get "/about", to: 'pages#about'

  resources :users, only: [:new, :create, :edit, :update, :show] do
    resources :bookings, only: [:index]
  end

  # Separate index page to display all the articles of an author (user)
  get 'dashboard', to: 'pages#dashboard'

  resources :articles do
    resources :reviews, only: [:new, :create]

    resources :bookings, only: [:show, :new, :create]
  end
end
